services:
  
  pgdatabase:
    container_name: pg-database
    image: postgres:13
    environment:
      - POSTGRES_USER=hi
      - POSTGRES_PASSWORD=hi
      - POSTGRES_DB=gdp
    volumes:
      - "./data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./data_pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80"